// Periodic Table Data with grid positions
const periodicTable = {
    // Period 1
    'H': { name: 'Hydrogen', number: 1, period: 1, group: 1 },
    'He': { name: 'Helium', number: 2, period: 1, group: 18 },
    
    // Period 2
    'Li': { name: 'Lithium', number: 3, period: 2, group: 1 },
    'Be': { name: 'Beryllium', number: 4, period: 2, group: 2 },
    'B': { name: 'Boron', number: 5, period: 2, group: 13 },
    'C': { name: 'Carbon', number: 6, period: 2, group: 14 },
    'N': { name: 'Nitrogen', number: 7, period: 2, group: 15 },
    'O': { name: 'Oxygen', number: 8, period: 2, group: 16 },
    'F': { name: 'Fluorine', number: 9, period: 2, group: 17 },
    'Ne': { name: 'Neon', number: 10, period: 2, group: 18 },
    
    // Period 3
    'Na': { name: 'Sodium', number: 11, period: 3, group: 1 },
    'Mg': { name: 'Magnesium', number: 12, period: 3, group: 2 },
    'Al': { name: 'Aluminum', number: 13, period: 3, group: 13 },
    'Si': { name: 'Silicon', number: 14, period: 3, group: 14 },
    'P': { name: 'Phosphorus', number: 15, period: 3, group: 15 },
    'S': { name: 'Sulfur', number: 16, period: 3, group: 16 },
    'Cl': { name: 'Chlorine', number: 17, period: 3, group: 17 },
    'Ar': { name: 'Argon', number: 18, period: 3, group: 18 },
    
    // Period 4
    'K': { name: 'Potassium', number: 19, period: 4, group: 1 },
    'Ca': { name: 'Calcium', number: 20, period: 4, group: 2 },
    'Sc': { name: 'Scandium', number: 21, period: 4, group: 3 },
    'Ti': { name: 'Titanium', number: 22, period: 4, group: 4 },
    'V': { name: 'Vanadium', number: 23, period: 4, group: 5 },
    'Cr': { name: 'Chromium', number: 24, period: 4, group: 6 },
    'Mn': { name: 'Manganese', number: 25, period: 4, group: 7 },
    'Fe': { name: 'Iron', number: 26, period: 4, group: 8 },
    'Co': { name: 'Cobalt', number: 27, period: 4, group: 9 },
    'Ni': { name: 'Nickel', number: 28, period: 4, group: 10 },
    'Cu': { name: 'Copper', number: 29, period: 4, group: 11 },
    'Zn': { name: 'Zinc', number: 30, period: 4, group: 12 },
    'Ga': { name: 'Gallium', number: 31, period: 4, group: 13 },
    'Ge': { name: 'Germanium', number: 32, period: 4, group: 14 },
    'As': { name: 'Arsenic', number: 33, period: 4, group: 15 },
    'Se': { name: 'Selenium', number: 34, period: 4, group: 16 },
    'Br': { name: 'Bromine', number: 35, period: 4, group: 17 },
    'Kr': { name: 'Krypton', number: 36, period: 4, group: 18 },
    
    // Period 5
    'Rb': { name: 'Rubidium', number: 37, period: 5, group: 1 },
    'Sr': { name: 'Strontium', number: 38, period: 5, group: 2 },
    'Y': { name: 'Yttrium', number: 39, period: 5, group: 3 },
    'Zr': { name: 'Zirconium', number: 40, period: 5, group: 4 },
    'Nb': { name: 'Niobium', number: 41, period: 5, group: 5 },
    'Mo': { name: 'Molybdenum', number: 42, period: 5, group: 6 },
    'Tc': { name: 'Technetium', number: 43, period: 5, group: 7 },
    'Ru': { name: 'Ruthenium', number: 44, period: 5, group: 8 },
    'Rh': { name: 'Rhodium', number: 45, period: 5, group: 9 },
    'Pd': { name: 'Palladium', number: 46, period: 5, group: 10 },
    'Ag': { name: 'Silver', number: 47, period: 5, group: 11 },
    'Cd': { name: 'Cadmium', number: 48, period: 5, group: 12 },
    'In': { name: 'Indium', number: 49, period: 5, group: 13 },
    'Sn': { name: 'Tin', number: 50, period: 5, group: 14 },
    'Sb': { name: 'Antimony', number: 51, period: 5, group: 15 },
    'Te': { name: 'Tellurium', number: 52, period: 5, group: 16 },
    'I': { name: 'Iodine', number: 53, period: 5, group: 17 },
    'Xe': { name: 'Xenon', number: 54, period: 5, group: 18 },
    
    // Period 6
    'Cs': { name: 'Cesium', number: 55, period: 6, group: 1 },
    'Ba': { name: 'Barium', number: 56, period: 6, group: 2 },
    'La': { name: 'Lanthanum', number: 57, period: 6, group: 3 },
    'Ce': { name: 'Cerium', number: 58, period: 8, group: 4 },
    'Pr': { name: 'Praseodymium', number: 59, period: 8, group: 5 },
    'Nd': { name: 'Neodymium', number: 60, period: 8, group: 6 },
    'Pm': { name: 'Promethium', number: 61, period: 8, group: 7 },
    'Sm': { name: 'Samarium', number: 62, period: 8, group: 8 },
    'Eu': { name: 'Europium', number: 63, period: 8, group: 9 },
    'Gd': { name: 'Gadolinium', number: 64, period: 8, group: 10 },
    'Tb': { name: 'Terbium', number: 65, period: 8, group: 11 },
    'Dy': { name: 'Dysprosium', number: 66, period: 8, group: 12 },
    'Ho': { name: 'Holmium', number: 67, period: 8, group: 13 },
    'Er': { name: 'Erbium', number: 68, period: 8, group: 14 },
    'Tm': { name: 'Thulium', number: 69, period: 8, group: 15 },
    'Yb': { name: 'Ytterbium', number: 70, period: 8, group: 16 },
    'Lu': { name: 'Lutetium', number: 71, period: 8, group: 17 },
    'Hf': { name: 'Hafnium', number: 72, period: 6, group: 4 },
    'Ta': { name: 'Tantalum', number: 73, period: 6, group: 5 },
    'W': { name: 'Tungsten', number: 74, period: 6, group: 6 },
    'Re': { name: 'Rhenium', number: 75, period: 6, group: 7 },
    'Os': { name: 'Osmium', number: 76, period: 6, group: 8 },
    'Ir': { name: 'Iridium', number: 77, period: 6, group: 9 },
    'Pt': { name: 'Platinum', number: 78, period: 6, group: 10 },
    'Au': { name: 'Gold', number: 79, period: 6, group: 11 },
    'Hg': { name: 'Mercury', number: 80, period: 6, group: 12 },
    'Tl': { name: 'Thallium', number: 81, period: 6, group: 13 },
    'Pb': { name: 'Lead', number: 82, period: 6, group: 14 },
    'Bi': { name: 'Bismuth', number: 83, period: 6, group: 15 },
    'Po': { name: 'Polonium', number: 84, period: 6, group: 16 },
    'At': { name: 'Astatine', number: 85, period: 6, group: 17 },
    'Rn': { name: 'Radon', number: 86, period: 6, group: 18 }
}; 